option(AIRBAG_FD "Use airbag_fd crash handler (only for unix)" FALSE)
option(FREETYPE "Use Freetype for font rendering" TRUE)
option(WITH_SYSTEM_FREETYPE "Use installed FreeType?  (Else build from source)" FALSE)
option(WITH_SYSTEM_LIBEV "Use installed libev?  (Else build from source)" FALSE)
option(WITH_SYSTEM_MXML "Use installed libmxml.so?  (Else build)" FALSE)
option(WITH_SYSTEM_ZLIB "Use installed zlib?  (Else build from source)" FALSE)
option(UX_FD "File descriptor user interface" TRUE)
option(UX_CDK "CDK (ncurses) user interface" FALSE)
option(UX_FB "Framebuffer user interface" TRUE)
option(SDL "SDL backend for the fb driver" TRUE)
option(FMT_EPUB "Support EPUB books" TRUE)
option(FMT_HTML "Support HTML books" TRUE)
option(FMT_JPEG "Support JPEG images" TRUE)
option(FMT_PNG  "Support PNG images" TRUE)
